### ISSUE TITLE
Statement importing fails unless links are made in the pfc directory to fixofx lib and 3rdparty directories

### ISSUE THREAD

**Issue by jmilum** [wesabe/fixofx#1]
I got the following error printed out to the rails terminal when trying to import a statement:

```
fixofx failed importing UNKNOWN statement from Bank (us-000840) with MakeOFX2::FatalError [filepath:  /var/wesabe/uploads/current/014/b9f/014b9fa772160bb3c06867f45388babd3fe7d723aa483f6ed416263f  76d41350/20100724000124-01.dat]
```

I was able to fix the problem by linking to the module directories in the fixofx directory from the pfc dirctory:

```
$ ln -s ../fixofx/3rdparty/ 3rdparty
$ cd lib
$ ln -s ../../fixofx/lib/* .
```

The import then worked correctly

**Comment by eventualbuddha** [comment]
What value are you using for `OFX_CONVERTER` in `pfc`?

**Comment by precipice** [comment]
I'm interested in the response to that question. I'll work on this tonight.

**Comment by jmilum** [comment]
I am using what is listed in the wiki:

```
silence_warnings do
  path = Rails.root.join('../fixofx/fixofx.py')
  OFX_CONVERTER = "python #{path}" if path.exist?
end
```

**Comment by precipice** [comment]
Thanks. I haven't tested the wiki config. It looks wrong to me - I'll try it out and correct it.

**Comment by nylen** [comment]
This is now fixed.  See https://github.com/wesabe/fixofx/commit/1b261652f562b98e0f5581646467cc9a46554f6b.

**Comment by jmilum** [comment]
Yes, this is fixed for me as well.

**Comment by precipice** [comment]
Fix confirmed. Thanks, nylen!
